# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 20
    commit-message:
      prefix: deps
    schedule:
      interval: weekly
      time: '00:30'
      day: thursday
    labels:
      - ci
      - priority-low
      - maintenance
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    open-pull-requests-limit: 20
    commit-message:
      prefix: deps
    schedule:
      interval: weekly
      time: '00:30'
      day: thursday
    labels:
      - dependencies
      - ci
      - priority-low
      - maintenance
    groups:
      npm-dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major
      - dependency-name: "eslint"
        update-types:
          - version-update:semver-major
      - dependency-name: "@typescript-eslint/eslint-plugin"
        update-types:
          - version-update:semver-major
      - dependency-name: "@typescript-eslint/parser"
        update-types:
          - version-update:semver-major
      - dependency-name: "conventional-changelog-conventionalcommits"
        update-types:
          - version-update:semver-major
