@apiUrl = http://127.0.0.1:8000
@token = YOUR_SECRET_TOKEN

### home
GET {{apiUrl}}/api/v0

### Add new form
PUT {{apiUrl}}/api/v0/form/?storage=test
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "filed1": "test1",
  "filed2": "test2",
  "filed13": "test3"
}

### Get storage
GET {{apiUrl}}/v0/form/storage?storage=test
Authorization: Bearer {{token}}


### === Test other routes and errors ===

### Page Home
GET {{apiUrl}}/v0

### Page 404 (wrong path)
GET {{apiUrl}}/v0/jafang

### Page 404 (wrong method)
POST {{apiUrl}}/v0

### Page health
GET {{apiUrl}}/v0/health

### empty body
PUT {{apiUrl}}/v0/form/?storage=test
Content-Type: application/json
Authorization: Bearer {{token}}

### invalid json
PUT {{apiUrl}}/v0/form/?storage=test
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "a": 1,
  b: 2,
}
