@apiUrl = http://127.0.0.1:8000/api/v0
@token = YOUR_SECRET_TOKEN

### home
GET {{apiUrl}}/

### Add new form
PUT {{apiUrl}}/form/?storage=test
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "filed1": "test1",
  "filed2": "test2",
  "filed13": "test3"
}

### Get storage
GET {{apiUrl}}/form/storage?storage=test
Authorization: Bearer {{token}}


### === Test other routes and errors ===

### Page Home
GET {{apiUrl}}/

### Page 404 (wrong path)
GET {{apiUrl}}/jafang

### Page 404 (wrong method)
POST {{apiUrl}}

### Page health
GET {{apiUrl}}/health

### empty body
PUT {{apiUrl}}/form/?storage=test
Content-Type: application/json
Authorization: Bearer {{token}}

### invalid json
PUT {{apiUrl}}/form/?storage=test
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "a": 1,
  b: 2,
}
