@apiUrl = http://127.0.0.1:8000
@apiVersion = v0
@token = YOUR_SECRET_TOKEN

### Home
GET {{apiUrl}}/

### New day downcount
PATCH {{apiUrl}}/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "chatId": "23029323"
}
