import './context-provider/chat-storage.js';
import './context-provider/home-page-content.js';
import './context-provider/l18e.js';
import './context-provider/order-storage.js';
import './context-provider/price-storage.js';
import './context-provider/product-storage.js';
import './context-provider/user.js';
import './controller/new-order.js';
import './submit-order-command-handler.js';
