@apiUrl = http://order.soffit.co/api/v0
@adminToken = ADMIN_SECRET_TOKEN

### Soffit product list
PATCH {{apiUrl}}/product-list/?storage=tile
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "data": [
    {
      "id": "1",
      "title": { "fa": "تایل کد ۰۰۱" },
      "image": { "id": "soffit-tile-1-1.jpg" }
    },
    {
      "id": "9",
      "title": { "fa": "تایل کد ۰۰۲" },
      "image": { "id": "soffit-tile-2-1.jpg" }
    },
    {
      "id": "10",
      "title": { "fa": "تایل کد ۰۰۵" },
      "image": { "id": "soffit-tile-5-1.jpg" }
    },
    {
      "id": "11",
      "title": { "fa": "تایل کد ۰۰۶" },
      "image": { "id": "soffit-tile-6-1.jpg" }
    },
    {
      "id": "12",
      "title": { "fa": "تایل کد ۰۰۷" },
      "image": { "id": "soffit-tile-7-1.jpg" }
    },
    {
      "id": "5",
      "title": { "fa": "تایل کد ۲۳۸" },
      "image": { "id": "soffit-tile-238-1.jpg" }
    },
    {
      "id": "2",
      "title": { "fa": "تایل کد ۲۳۸G" },
      "image": { "id": "soffit-tile-238G-1.jpg" }
    },
    {
      "id": "6",
      "title": { "fa": "تایل کد ۲۳۹" },
      "image": { "id": "soffit-tile-239-1.jpg" }
    },
    {
      "id": "13",
      "title": { "fa": "تایل کد ۹۷۵" },
      "image": { "id": "soffit-tile-975-1.jpg" }
    },
    {
      "id": "7",
      "title": { "fa": "تایل کد ۹۹۳" },
      "image": { "id": "soffit-tile-993-1.jpg" }
    },
    {
      "id": "8",
      "title": { "fa": "تایل کد ۹۹۶" },
      "image": { "id": "soffit-tile-996-1.jpg" }
    },
    {
      "id": "3",
      "title": { "fa": "تایل کد ۹۹۶G" },
      "image": { "id": "soffit-tile-996G-1.jpg" }
    },
    {
      "id": "4",
      "title": { "fa": "تایل کد ۳۳۳" },
      "image": { "id": "soffit-tile-333-1.jpg" }
    }
  ]
}

### Insert/edit a product price of special list.
PATCH {{apiUrl}}/price-list/?name=tile-market-ir
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "data": [
    {
      "id": "1",
      "price": 83000
    },
    {
      "id": "2",
      "price": 85000
    },
    {
      "id": "3",
      "price": 85000
    },
    {
      "id": "4",
      "price": 85000
    },
    {
      "id": "5",
      "price": 77100
    },
    {
      "id": "6",
      "price": 77100
    },
    {
      "id": "7",
      "price": 77100
    },
    {
      "id": "8",
      "price": 77100
    },
    {
      "id": "9",
      "price": 83000
    },
    {
      "id": "10",
      "price": 83000
    },
    {
      "id": "11",
      "price": 85000
    },
    {
      "id": "12",
      "price": 85000
    },
    {
      "id": "13",
      "price": 77100
    }
  ]
}

### Insert/edit a product price of special list.
PATCH {{apiUrl}}/price-list/?name=tile-agency-ir
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "data": [
    {
      "id": "1",
      "price": 72210
    },
    {
      "id": "2",
      "price": 73950
    },
    {
      "id": "3",
      "price": 73950
    },
    {
      "id": "4",
      "price": 73950
    },
    {
      "id": "5",
      "price": 66306
    },
    {
      "id": "6",
      "price": 66306
    },
    {
      "id": "7",
      "price": 66306
    },
    {
      "id": "8",
      "price": 66306
    },
    {
      "id": "9",
      "price": 72210
    },
    {
      "id": "10",
      "price": 72210
    },
    {
      "id": "11",
      "price": 73950
    },
    {
      "id": "12",
      "price": 73950
    },
    {
      "id": "13",
      "price": 66306
    }
  ]
}
