@apiUrl = http://127.0.0.1:8000
@apiVersion = v0
@token = YOUR_SECRET_TOKEN

### home
GET {{apiUrl}}/

### New Vow
POST {{apiUrl}}/vow
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "count": 30
}
