// import '@ionic/core/dist/types/components';
import {initialize} from '@ionic/core/components';
import {defineCustomElement as ionAlert} from '@ionic/core/components/ion-alert.js';
import {defineCustomElement as ionApp} from '@ionic/core/components/ion-app.js';
import {defineCustomElement as ionAvatar} from '@ionic/core/components/ion-avatar.js';
import {defineCustomElement as ionBackdrop} from '@ionic/core/components/ion-backdrop.js';
import {defineCustomElement as ionButton} from '@ionic/core/components/ion-button.js';
import {defineCustomElement as ionButtons} from '@ionic/core/components/ion-buttons.js';
import {defineCustomElement as ionCardContent} from '@ionic/core/components/ion-card-content.js';
import {defineCustomElement as ionCardHeader} from '@ionic/core/components/ion-card-header.js';
import {defineCustomElement as ionCardSubtitle} from '@ionic/core/components/ion-card-subtitle.js';
import {defineCustomElement as ionCardTitle} from '@ionic/core/components/ion-card-title.js';
import {defineCustomElement as ionCard} from '@ionic/core/components/ion-card.js';
import {defineCustomElement as ionCol} from '@ionic/core/components/ion-col.js';
import {defineCustomElement as ionContent} from '@ionic/core/components/ion-content.js';
import {defineCustomElement as ionFabButton} from '@ionic/core/components/ion-fab-button.js';
import {defineCustomElement as ionFab} from '@ionic/core/components/ion-fab.js';
import {defineCustomElement as ionFooter} from '@ionic/core/components/ion-footer.js';
import {defineCustomElement as ionGrid} from '@ionic/core/components/ion-grid.js';
import {defineCustomElement as ionHeader} from '@ionic/core/components/ion-header.js';
import {defineCustomElement as ionInput} from '@ionic/core/components/ion-input.js';
import {defineCustomElement as ionItemOption} from '@ionic/core/components/ion-item-option.js';
import {defineCustomElement as ionItemOptions} from '@ionic/core/components/ion-item-options.js';
import {defineCustomElement as ionItemSliding} from '@ionic/core/components/ion-item-sliding.js';
import {defineCustomElement as ionItem} from '@ionic/core/components/ion-item.js';
import {defineCustomElement as ionLabel} from '@ionic/core/components/ion-label.js';
import {defineCustomElement as ionListHeader} from '@ionic/core/components/ion-list-header.js';
import {defineCustomElement as ionList} from '@ionic/core/components/ion-list.js';
import {defineCustomElement as ionLoading} from '@ionic/core/components/ion-loading.js';
import {defineCustomElement as ionModal} from '@ionic/core/components/ion-modal.js';
import {defineCustomElement as ionNote} from '@ionic/core/components/ion-note.js';
import {defineCustomElement as ionRadioGroup} from '@ionic/core/components/ion-radio-group.js';
import {defineCustomElement as ionRadio} from '@ionic/core/components/ion-radio.js';
import {defineCustomElement as ionRow} from '@ionic/core/components/ion-row.js';
import {defineCustomElement as ionSearchbar} from '@ionic/core/components/ion-searchbar.js';
import {defineCustomElement as ionSegmentButton} from '@ionic/core/components/ion-segment-button.js';
import {defineCustomElement as ionSegment} from '@ionic/core/components/ion-segment.js';
import {defineCustomElement as ionSelectOption} from '@ionic/core/components/ion-select-option.js';
import {defineCustomElement as ionSelect} from '@ionic/core/components/ion-select.js';
import {defineCustomElement as ionSkeletonText} from '@ionic/core/components/ion-skeleton-text.js';
import {defineCustomElement as ionSpinner} from '@ionic/core/components/ion-spinner.js';
import {defineCustomElement as ionTabBar} from '@ionic/core/components/ion-tab-bar.js';
import {defineCustomElement as ionTabButton} from '@ionic/core/components/ion-tab-button.js';
import {defineCustomElement as ionText} from '@ionic/core/components/ion-text.js';
import {defineCustomElement as ionTextarea} from '@ionic/core/components/ion-textarea.js';
import {defineCustomElement as ionThumbnail} from '@ionic/core/components/ion-thumbnail.js';
import {defineCustomElement as ionTitle} from '@ionic/core/components/ion-title.js';
import {defineCustomElement as ionToast} from '@ionic/core/components/ion-toast.js';
import {defineCustomElement as ionToolbar} from '@ionic/core/components/ion-toolbar.js';

initialize();

ionAlert();
ionApp();
ionAvatar();
ionBackdrop();
ionButton();
ionButtons();
ionCard();
ionCardContent();
ionCardHeader();
ionCardSubtitle();
ionCardTitle();
ionCol();
ionContent();
ionFab();
ionFabButton();
ionFooter();
ionGrid();
ionHeader();
ionInput();
ionItem();
ionItemOption();
ionItemOptions();
ionItemSliding();
ionLabel();
ionList();
ionListHeader();
ionLoading();
ionModal();
ionNote();
ionRadio();
ionRadioGroup();
ionRow();
ionSearchbar();
ionSegment();
ionSegmentButton();
ionSelect();
ionSelectOption();
ionSkeletonText();
ionSpinner();
ionTabBar();
ionTabButton();
ionText();
ionTextarea();
ionThumbnail();
ionTitle();
ionToast();
ionToolbar();
