/* eslint-disable max-len */
import {html} from '@alwatr/element';

import type {IconBoxContent} from '@alwatr/ui-kit/src/card/icon-box.js';

export interface BoxType extends IconBoxContent {
  wide?: boolean;
  content?: unknown;
  small?: boolean;
}

// Record<string, BoxType | Array<BoxType>>
export const homePageContent = {
  about: {
    wide: true,
    elevated: 1,
    stated: true,
    icon: 'logo-microsoft',
    headline: 'بازرگانی سافیت',
    content: html`
      سافیت با هدف بهینه سازی در ساخت وساز و همچنین کاهش هزینه ها تامین و نگه داری ساختمان در بلند مدت اقدام به تولید محصولات گچی نمود.<br/>
      همچنین با توجه به گسترش بازار و نیاز مشتریان تنوع طرح و جنس محصولات خود را افزایش داده است.
      از مزایا سقف ها سافیت می‌توان به سرعت بالا در اجرا، عایق صوت، رطوبت و حرارت نام برد. همچنین می‌توان به راحتی در دسترسی به تاسیسات نیز اشاره کرد.<br/>
      سافیت در نظر دارد سهم خود را در استفاده از،مواد اولیه  تجدید پذیر در تولید جهت حفظ و نگهداری محیط زیست برای آیندگان افزایش دهد.
    `,
  },

  catalogue: {
    elevated: 2,
    highlight: true,
    stated: true,
    icon: 'cloud-download-outline',
    headline: 'دانلود کاتالوگ',
    description: 'دانلود کاتالوگ معرفی محصولات بازرگانی سافیت',
    href: 'https://www.dropbox.com/s/6ywy23qql7iq31p/soffit-product-catalogue.pdf?dl=1',
    target: 'download',
  },

  contact: {
    elevated: 2,
    highlight: true,
    stated: true,
    icon: 'call-outline',
    flipRtl: true,
    headline: 'تماس با ما',
    description: 'دفتر مرکزی: ۰۹۱۵۵۵۹۹۶۷۴',
    href: 'tel:+989155599674',
  },

  productList: [
    {
      icon: 'grid-outline',
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'سقف کاذب',
      description: 'متن توضیحات...',
      wide: true,
    },
    {
      icon: 'git-commit-outline',
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'سازه‌ و‌ اتصالات',
      description: 'متن توضیحات...',
    },
    {
      icon: 'bulb-outline',
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'روشنایی',
      description: 'متن توضیحات...',
    },
  ],

  socialList: [
    {
      elevated: 2,
      highlight: true,
      stated: true,
      icon: 'logo-instagram',
      headline: 'اینستاگرام',
      description: 'صفحه‌ی اینستاگرام بازرگانی سافیت',
      href: 'https://instagram.com/soffit.co',
      target: '_blank',
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      icon: 'send-outline',
      headline: 'تلگرام',
      description: 'کانال تلگرام بازرگانی سافیت',
      href: 'https://t.me/soffitcompany',
      target: '_blank',
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      icon: 'logo-linkedin',
      headline: 'لینکدین',
      description: 'صفحه‌ی لینکدین بازرگانی سافیت',
      href: 'https://www.linkedin.com/company/soffit-co',
      target: '_blank',
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      icon: 'videocam-outline',
      headline: 'آپارات',
      description: 'کانال آپارات بازرگانی سافیت',
      href: 'https://www.aparat.com/soffit',
      target: '_blank',
    },
  ],

  agencyList: [
    {
      elevated: 1,
      stated: true,
      icon: 'ribbon-outline',
      headline: 'نمایندگی‌ها',
      description: 'لیست نمایندگی‌ها سافیت در سراسر کشور',
      wide: true,
    },
    // {
    //   elevated: 2,
    //   highlight: true,
    //   stated: true,
    //   headline: 'شعبه مرکزی',
    //   description: `تلفن‌‌ تماس: ۰۹۱۵۳۰۱۴۴۰۴`,
    //   href: 'tel:+989153014404',
    // },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'کردستان',
      description: 'آقای صفایی: ۰۹۱۴۳۸۱۳۹۲۵',
      href: 'tel:+989143813925',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'گلستان',
      description: 'آقای اقلچی: ۰۹۱۱۷۵۰۵۰۲۷',
      href: 'tel:+989117505027',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'ایلام',
      description: 'آقای صیدی: ۰۹۱۸۳۴۲۸۹۰۳',
      href: 'tel:+989183428903',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'آذربایجان‌غربی',
      description: 'آقای صفایی: ۰۹۱۴۳۸۱۳۹۲۵',
      href: 'tel:+989143813925',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'خراسان‌جنوبی',
      description: 'آقای محبی: ۰۹۱۵۵۰۶۹۲۰۸',
      href: 'tel:+989155069208',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'زاهدان',
      description: 'آقای قاسمی: ۰۹۱۵۵۴۰۹۶۲۰',
      href: 'tel:+989155409620',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'کرمانشاه',
      description: 'آقای حاجتی: ۰۹۱۸۵۵۹۰۴۳۱',
      href: 'tel:+989185590431',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'کرمان',
      description: 'آقای رضایی: ۰۹۱۳۵۶۳۱۷۱۱',
      href: 'tel:+989135631711',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'همدان',
      description: 'آقای طهماسبی: ۰۹۱۸۵۴۴۰۵۲۷',
      href: 'tel:+989185540527',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'همدان',
      description: 'آقای طهماسبی: ۰۹۱۸۵۴۴۰۵۲۷',
      href: 'tel:+989185540527',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'خراسان‌رضوی',
      description: 'آقای محبی: ۰۹۱۵۵۰۶۹۲۰۸',
      href: 'tel:+989155069208',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'خراسان‌شمالی',
      description: 'آقای محبی: ۰۹۱۵۵۰۶۹۲۰۸',
      href: 'tel:+989155069208',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'اصفهان',
      description: 'آقای بهنام‌پور: ۰۹۱۳۳۳۹۱۸۲۸',
      href: 'tel:+989133391828',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'سمنان',
      description: 'آقای حافظی: ۰۹۱۹۲۷۶۰۸۰۶',
      href: 'tel:+989192760806',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'کیش',
      description: 'آقای سالاری: ۰۹۹۰۳۴۹۸۴۲۵',
      href: 'tel:+989903498425',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'زنجان',
      description: 'آقای نقی‌لو: ۰۹۱۲۰۶۷۶۵۰۳',
      href: 'tel:+989120676503',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'اردبیل',
      description: 'آقای پاسبانی: ۰۹۱۴۱۵۰۴۲۰۳',
      href: 'tel:+989141504203',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'بندرعباس',
      description: 'آقای کمالی‌پور: ۰۹۳۰۳۸۰۰۱۳۴',
      href: 'tel:+989303800134',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'چهارمحال‌ و‌ بختیاری',
      description: 'آقای فروزنده: ۰۹۱۳۲۸۳۹۱۹۳',
      href: 'tel:+989132839193',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'کهگیلویه‌ و‌ بویراحمد',
      description: 'آقای عظیمی‌فر: ۰۹۱۷۴۳۲۶۱۳۲',
      href: 'tel:+989174326132',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'آذربایجان‌شرقی',
      description: 'آقای سلیمانی: ۰۹۳۵۷۰۷۱۹۰۴',
      href: 'tel:+989357071904',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'شیراز',
      description: 'آقای خدامی: ۰۹۱۷۱۱۳۲۲۶۲',
      href: 'tel:+989171132262',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'خوزستان',
      description: 'آقای شمس: ۰۹۱۶۶۰۳۳۶۱۲',
      href: 'tel:+989166033612',
      // small: true,
    },
    {
      elevated: 2,
      highlight: true,
      stated: true,
      headline: 'ورامین',
      description: 'آقای بیدگلی: ۰۹۹۰۳۷۳۰۳۷۷',
      href: 'tel:+989903730377',
      // small: true,
    },
  ],
} as const;
