@apiUrl = http://127.0.0.1:8000
@apiVersion = v0
@token = YOUR_SECRET_TOKEN

### home
GET {{apiUrl}}/

### Add new comment
PUT {{apiUrl}}/meta
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "Urqxnat.png",
  "meta": {
    "order": 2,
    "description": "test photo"
  }
}
