@apiUrl = http://127.0.0.1:8000
@apiVersion = v0
@token = alwatr_110_313

# Add job
PUT {{apiUrl}}/{{apiVersion}}/job/add
authorization: Bearer {{token}}
Content-Type: application/json

{
  "origin": "KIH",
  "dest": "THR",
  "date": "1401/10/10"
}


DELETE {{apiUrl}}/{{apiVersion}}/job/delete?id=1
authorization: Bearer {{token}}


GET {{apiUrl}}/{{apiVersion}}/job/current
authorization: Bearer {{token}}

