@apiUrl = http://127.0.0.1:8000
@apiVersion = v0
@token = alwatr_110_313

GET {{apiUrl}}/{{apiVersion}}/current
authorization: Bearer {{token}}

DELETE {{apiUrl}}/{{apiVersion}}/delete?id=df2d806e
authorization: Bearer {{token}}

## Add job
PATCH {{apiUrl}}/{{apiVersion}}/add
authorization: Bearer {{token}}
Content-Type: application/json

{
  "origin": "KIH",
  "dest": "THR",
  "date": "1401/10/10"
}
