# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build & Lint

on:
  workflow_dispatch:

  pull_request:

  push:
    branches:
      - next

env:
  BUN_VERSION: latest

jobs:
  build-lint-ts:
    name: Build & Lint Typescript
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v7

      - name: 🏗 Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      # - name: 🏗 Setup nodejs corepack
      #   run: corepack enable

      # - name: 🏗 Cache Layer
      #   uses: actions/cache@v5
      #   with:
      #     path: ~/.bun/install/cache
      #     key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-bun-

      - name: 🏗 Install dependencies
        run: |
          bun --version
          bun ci

      - name: 🚀 Build Typescript
        run: bun run build

      - name: 🚀 Run ESLint
        run: bun run lint

      - name: 🚀 Run Tests
        run: bun run test
