# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build & Publish Containers

on:
  workflow_dispatch:

  push:
    branches:
      - next

  pull_request:

  release:
    types:
      - created

env:
  USER: alwatr

jobs:
  build:
    if: github.repository_owner == 'Alwatr'

    name: Build & Publish Containers
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: nitrobase-nginx
            path: ./packages/nherit
            context: ./packages/nherit

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v4.2.2

      - name: ❔ Check Container files changed
        id: file_change
        if: ${{ github.event_name != 'release' && github.event_name != 'workflow_dispatch' }}
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            container_folder:
              ./${{ matrix.context }}/**

      - name: 🏗 Install cosign
        if: ${{ github.event_name != 'pull_request' && steps.file_change.outputs.container_folder != 'false' }}
        uses: sigstore/cosign-installer@v3.8.1

      - name: 🏗 Setup Docker Buildx
        if: ${{ steps.file_change.outputs.container_folder != 'false' }}
        uses: docker/setup-buildx-action@v3.10.0

      - name: 🏗 Cache Docker Layers
        if: ${{ steps.file_change.outputs.container_folder != 'false' }}
        uses: actions/cache@v4.2.2
        with:
          path: /tmp/.buildx-cache
          key: container/${{ matrix.name }}

      - name: 🏗 Log into docker hub registry
        if: ${{ github.event_name != 'pull_request' && steps.file_change.outputs.container_folder != 'false' }}
        uses: docker/login-action@v3.3.0
        with:
          username: ${{env.USER}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: 🏗 Log into ghcr.io registry
        if: ${{ github.event_name != 'pull_request' && steps.file_change.outputs.container_folder != 'false' }}
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{env.USER}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 🏗 Extract metadata
        if: ${{ steps.file_change.outputs.container_folder != 'false' }}
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          images: |
            name=ghcr.io/${{env.USER}}/${{matrix.name}},enable=true
            name=docker.io/${{env.USER}}/${{matrix.name}},enable=true
          tags: |
            type=semver,enable=true,pattern={{major}}
            type=semver,enable=true,pattern={{major}}.{{minor}}
            type=semver,enable=true,pattern={{version}}
            type=ref,enable=true,event=branch

      - name: 🚀 Build and export to docekr
        if: ${{ steps.file_change.outputs.container_folder != 'false' }}
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./${{matrix.context}}
          file: ${{matrix.path}}/Dockerfile
          push: false
          load: true
          tags: ${{env.USER}}/${{matrix.name}}:test
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: 🧪 Nherit config test
        if: ${{ steps.file_change.outputs.container_folder != 'false' && contains(matrix.name, 'nherit') }}
        run: |
          echo "Running tests for ${{matrix.name}}"
          docker run --rm -e TEST_MODE=1 ${{env.USER}}/${{matrix.name}}:test /etc/nginx/entrypoint.sh nginx -T -c /etc/nginx/nginx.conf

      # TODO: 🧪 Api test

      - name: 🚀 Build and publish container image
        if: ${{ steps.file_change.outputs.container_folder != 'false' }}
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./${{matrix.context}}
          file: ${{matrix.path}}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            BUILD_DATE=${{github.event.repository.updated_at}}
            BUILD_REV=${{github.sha}}
