# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish NPM

on:
  workflow_dispatch:
  release:
    types:
      - created

env:
  BUN_VERSION: latest

jobs:
  publish-npm:
    name: Publish NPM
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v7

      - name: 🏗 Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: 🔐 Configure NPM authentication and verify
        run: |
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> .npmrc
          bun pm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 🏗 Install dependencies
        run: |
          bun --version
          bun ci

      - name: 🚀 Build Typescript
        run: bun run build

      - name: 🚀 Publish
        run: bun run publish --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}